
server:
  port: 8181

spring:
  application:
    name: auth-service

  cloud:
    config:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8988

  main:
    lazy-initialization: true

  data:
    redis:
      host: localhost
      port: 6380

  mail:
    host: localhost
    port: 1027

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expirationMs: 86400000

application:
  config:
    organisation-service: http://localhost:8190
