server:
  port: 8861

spring:
  application:
    name: discovery-service

  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true

  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8861/eureka/

  server:
    enable-self-preservation: false
