services:

  postgres:
    container_name: weentime-project-postgres
    image: postgres:17
    environment:
      POSTGRES_USER: weentime
      POSTGRES_PASSWORD: 170502
      POSTGRES_DB: weentime
    ports:
      - "5433:5432"
    volumes:
      - weentime-project-postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - weentime-network
    restart: unless-stopped

  redis:
    container_name: weentime-project-redis
    image: redis:7
    ports:
      - "6380:6379"
    networks:
      - weentime-network
    restart: unless-stopped

  pgadmin:
    container_name: weentime-project-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5052:80"
    volumes:
      - weentime-project-pgadmin-data:/var/lib/pgadmin
    networks:
      - weentime-network
    restart: unless-stopped

  mail_dev:
    container_name: weentime-project-maildev
    image: maildev/maildev
    ports:
      - "1082:1080"
      - "1027:1025"
    networks:
      - weentime-network
    restart: unless-stopped

networks:
  weentime-network:

volumes:
  weentime-project-postgres-data:
  weentime-project-pgadmin-data: