import { ApplicationConfig, LOCALE_ID } from '@angular/core';
import { PreloadAllModules, provideRouter, withComponentInputBinding, withPreloading, withViewTransitions } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { apiErrorInterceptor } from './core/interceptors/api-error.interceptor';
import { loadingInterceptorFn } from './core/interceptors/loading.interceptor.fn';
import { registerLocaleData } from '@angular/common';
import localeFr from '@angular/common/locales/fr';

registerLocaleData(localeFr);

import {
  Activity,
  AlarmClock,
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowRightCircle,
  Award,
  BadgeCheck,
  Banknote,
  BarChart,
  BarChart3,
  BarChart2,
  Baby,
  Bell,
  BellOff,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarOff,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  CircleCheck,
  CircleX,
  CircleAlert,
  CircleMinus,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Clock3,
  Clock10,
  Code,
  Coffee,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  Factory,
  FileCheck,
  FileCheck2,
  FileStack,
  FilePlus,
  FileSignature,
  FileText,
  Filter,
  Flame,
  FolderOpen,
  GitBranch,
  Github,
  Globe,
  Hash,
  Headset,
  HelpCircle,
  Heart,
  HeartPulse,
  Home,
  Hourglass,
  History,
  Inbox,
  Instagram,
  Info,
  Key,
  KeyRound,
  Laptop,
  Kanban,
  Layers,
  Layout,
  LayoutGrid,
  LayoutDashboard,
  Leaf,
  Link,
  Logs,
  Linkedin,
  Loader,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  List,
  LUCIDE_ICONS,
  LucideIconProvider,
  LucideAngularModule,
  Mail,
  MapPin,
  MessageSquare,
  Menu,
  Mic,
  MicOff,
  MinusCircle,
  Move,
  Moon,
  MoreVertical,
  MousePointerClick,
  Monitor,
  Network,
  PanelLeft,
  PanelLeftClose,
  Paperclip,
  Phone,
  PiggyBank,
  Pencil,
  Play,
  Power,
  Receipt,
  RefreshCw,
  Plus,
  RotateCcw,
  Save,
  Search,
  Send,
  SendHorizontal,
  Settings,
  Settings2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  Slash,
  ShoppingCart,
  Smartphone,
  Star,
  Sparkles,
  Stethoscope,
  Sun,
  Square,
  Sunrise,
  Sunset,
  Tent,
  Timer,
  TimerReset,
  Target,
  Trash2,
  TriangleAlert,
  TrendingDown,
  TrendingUp,
  Twitter,
  Type,
  Umbrella,
  Upload,
  User,
  UserCog,
  UserCheck,
  UserPlus,
  UserMinus,
  UserX,
  Users,
  Users2,
  Volume2,
  Wallet,
  Wifi,
  WifiOff,
  X,
  XCircle as XCircleIcon,
  Zap,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Bold,
  Italic,
  Underline,
  ListOrdered,
  Bot,
  GitMerge,
  BellRing,
  IdCard,
  PanelRightClose,
  PanelRightOpen,
  PenTool,
  PenLine,
  FilePen
} from 'lucide-angular';

const allIcons = {
  Activity,
  AlarmClock,
  AlertCircle,
  AlertTriangle,
  'alert-triangle': AlertTriangle,
  ArrowLeft,
  ArrowRight,
  'arrow-right': ArrowRight,
  ArrowRightCircle,
  Award,
  BadgeCheck,
  Baby,
  Banknote,
  BarChart,
  BarChart3,
  'bar-chart-3': BarChart3,
  BarChart2,
  'bar-chart-2': BarChart2,
  Bell,
  BellOff,
  BellRing,
  'bell-ring': BellRing,
  'bellRing': BellRing,
  BookOpen,
  Bot,
  bot: Bot,
  Briefcase,
  Building,
  Building2,
  'building-2': Building2,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  'calendar-days': CalendarDays,
  CalendarOff,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  'check-circle-2': CheckCircle2,
  CircleCheck,
  CheckCircle: CircleCheck, // Alias for legacy usage
  CircleX,
  XCircle: CircleX, // Alias for legacy usage
  CircleAlert,
  CircleMinus,
  'circle-minus': CircleMinus,
  'circleMinus': CircleMinus,
  AlertCircleAlias: AlertCircle,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  'chevron-right': ChevronRight,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Clock3,
  Clock10,
  Code,
  Coffee,
  Copy,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  Facebook,
  Factory,
  FileCheck,
  'file-check': FileCheck,
  FileCheck2,
  FileStack,
  FilePlus,
  FileSignature,
  'file-signature': FileSignature,
  FileText,
  'file-text': FileText,
  Filter,
  Flame,
  FolderOpen,
  GitBranch,
  GitMerge,
  'git-merge': GitMerge,
  'gitMerge': GitMerge,
  Github,
  Globe,
  Hash,
  Headset,
  HelpCircle,
  Heart,
  HeartPulse,
  'heart-pulse': HeartPulse,
  'heartPulse': HeartPulse,
  Home,
  home: Home,
  Hourglass,
  History,
  IdCard,
  'id-card': IdCard,
  'idCard': IdCard,
  Inbox,
  Instagram,
  Info,
  Key,
  KeyRound,
  Laptop,
  Kanban,
  Layers,
  Layout,
  LayoutGrid,
  LayoutDashboard,
  'layout-dashboard': LayoutDashboard,
  Leaf,
  Link,
  Logs,
  Linkedin,
  Loader,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  List,
  Mail,
  MapPin,
  'map-pin': MapPin,
  MessageSquare,
  Menu,
  Mic,
  MicOff,
  MinusCircle,
  Move,
  Moon,
  MoreVertical,
  MousePointerClick,
  Monitor,
  Network,
  PanelLeft,
  PanelLeftClose,
  Paperclip,
  paperclip: Paperclip,
  Phone,
  PiggyBank,
  Pencil,
  Play,
  Power,
  Plus,
  Receipt,
  RefreshCw,
  RotateCcw,
  Save,
  Search,
  Send,
  SendHorizontal,
  Settings,
  Settings2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  'shield-check': ShieldCheck,
  ShieldOff,
  Slash,
  ShoppingCart,
  'shopping-cart': ShoppingCart,
  Smartphone,
  Star,
  Sparkles,
  Stethoscope,
  Sun,
  Square,
  Timer,
  TimerReset,
  Target,
  Tent,
  Sunrise,
  Sunset,
  Trash2,
  TriangleAlert,
  TrendingDown,
  TrendingUp,
  'trending-up': TrendingUp,
  Twitter,
  Type,
  Umbrella,
  Upload,
  User,
  UserCog,
  UserCheck,
  UserPlus,
  'user-plus': UserPlus,
  UserMinus,
  UserX,
  Users,
  Users2,
  Volume2,
  Wallet,
  Wifi,
  WifiOff,
  X,
  Zap,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Bold,
  Italic,
  Underline,
  ListOrdered,
  PanelRightClose,
  PanelRightOpen,
  PenTool,
  'pen-tool': PenTool,
  PenLine,
  FilePen
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes,
      withComponentInputBinding(),
      withPreloading(PreloadAllModules)
    ),
    provideAnimationsAsync(),
    provideHttpClient(withInterceptors([loadingInterceptorFn, authInterceptor, apiErrorInterceptor])),
    { provide: LOCALE_ID, useValue: 'fr' },
    { provide: LUCIDE_ICONS, multi: true, useValue: new LucideIconProvider(allIcons) }
  ]
};
