spring:
  config:
    import: optional:configserver:http://localhost:8988
  application:
    name: discovery-service
  
server:
  port: 8861























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































