

CREATE TABLE public.departements (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code_interne character varying(255),
    description character varying(255),
    nom character varying(255) NOT NULL,
    entreprise_id bigint
);


CREATE TABLE public.entreprises (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    adresse character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    est_active boolean NOT NULL,
    nom character varying(255) NOT NULL,
    siret character varying(255) NOT NULL,
    site_web character varying(255),
    telephone character varying(255)
);



CREATE TABLE public.equipes (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description character varying(255),
    effectif_maximum integer,
    est_active boolean NOT NULL,
    nom character varying(255) NOT NULL,
    responsable_id bigint,
    departement_id bigint,
    created_at timestamp(6) without time zone
);



CREATE TABLE public.roles (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description character varying(255),
    nom character varying(255) NOT NULL,
    CONSTRAINT roles_nom_check CHECK (nom IN ('ROLE_EMPLOYEE', 'ROLE_MANAGER', 'ROLE_RH', 'ROLE_ADMIN'))
);


CREATE TABLE public.tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone,
    date_expiration timestamp(6) without time zone,
    date_validation time(0) without time zone,
    token character varying(255) NOT NULL,
    utilisateur_id bigint NOT NULL
);



CREATE TABLE public.user_audit_logs (
                                        id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        action character varying(255) NOT NULL,
                                        details character varying(255),
                                        performed_by character varying(255) NOT NULL,
                                        target_user character varying(255) NOT NULL,
                                        created_at timestamp(6) without time zone NOT NULL
);



CREATE TABLE public.utilisateur_roles (
    utilisateur_id bigint NOT NULL,
    role_id bigint NOT NULL
);



CREATE TABLE public.utilisateurs (
                                     id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     date_creation timestamp(6) without time zone NOT NULL,
                                     date_modification timestamp(6) without time zone,
                                     email character varying(255) NOT NULL,
                                     mot_de_passe character varying(255) NOT NULL,
                                     nom character varying(255) NOT NULL,
                                     poste character varying(255),
                                     prenom character varying(255) NOT NULL,
                                     statut character varying(255) NOT NULL,
                                     telephone character varying(255),
                                     departement_id bigint,
                                     equipe_id bigint,
                                     entreprise_id bigint,
                                     CONSTRAINT utilisateurs_statut_check CHECK (statut IN ('ACTIF','INACTIF','SUSPENDU','PENDING'))
);



ALTER TABLE public.departements
    ADD CONSTRAINT departements_pkey PRIMARY KEY (id);



ALTER TABLE public.entreprises
    ADD CONSTRAINT entreprises_pkey PRIMARY KEY (id);



ALTER TABLE public.equipes
    ADD CONSTRAINT equipes_pkey PRIMARY KEY (id);


ALTER TABLE public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);



ALTER TABLE public.tokens
    ADD CONSTRAINT tokens_pkey PRIMARY KEY (id);


ALTER TABLE public.utilisateurs
    ADD CONSTRAINT utilisateurs_pkey PRIMARY KEY (id);


ALTER TABLE public.utilisateurs
    ADD CONSTRAINT uk6ldvumu3hqvnmmxy1b6lsxwqy UNIQUE (email);



ALTER TABLE public.roles
    ADD CONSTRAINT ukbbxiq3fbrr32wfkco6ichxaly UNIQUE (nom);



ALTER TABLE public.entreprises
    ADD CONSTRAINT ukrgxkwkg4800o2wrfp95d33910 UNIQUE (siret);



ALTER TABLE public.departements
    ADD CONSTRAINT ukrxbr4e9qmyqkseex3edd14mgs UNIQUE (code_interne);



ALTER TABLE public.user_audit_logs
    ADD CONSTRAINT user_audit_logs_pkey PRIMARY KEY (id);



ALTER TABLE public.utilisateur_roles
    ADD CONSTRAINT utilisateur_roles_pkey PRIMARY KEY (utilisateur_id, role_id);



ALTER TABLE public.utilisateurs
    ADD CONSTRAINT fk_utilisateur_entreprise
        FOREIGN KEY (entreprise_id)
            REFERENCES public.entreprises(id);



ALTER TABLE public.tokens
    ADD CONSTRAINT fk3iky85n0ywh6weuof08cl7kn2 FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateurs(id);



ALTER TABLE public.utilisateurs
    ADD CONSTRAINT fk67103ihinblji0me5cpiee0bb FOREIGN KEY (departement_id) REFERENCES public.departements(id);



ALTER TABLE public.utilisateurs
    ADD CONSTRAINT fk7129eia1wfevrrvyhetkf8pkf FOREIGN KEY (equipe_id) REFERENCES public.equipes(id);



ALTER TABLE public.utilisateur_roles
    ADD CONSTRAINT fk7fm9de8itma0gr6wpblfr5o0o FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateurs(id);



ALTER TABLE public.equipes
    ADD CONSTRAINT fkh210lyxfpis34ws7b02593g3b FOREIGN KEY (departement_id) REFERENCES public.departements(id);



ALTER TABLE public.equipes
    ADD CONSTRAINT fkmnb3ac86ebn0u4lumo6i8mlhf FOREIGN KEY (responsable_id) REFERENCES public.utilisateurs(id);



ALTER TABLE public.utilisateur_roles
    ADD CONSTRAINT fkpvb9dvcn9icrukism9we0knub FOREIGN KEY (role_id) REFERENCES public.roles(id);


ALTER TABLE public.departements
    ADD CONSTRAINT fks7b069konicq2ifdi6ruhaad6 FOREIGN KEY (entreprise_id) REFERENCES public.entreprises(id);





