-- Presence management base table
CREATE TABLE presences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT NOT NULL,
    date_presence DATE NOT NULL,
    heure_entree TIMESTAMP,
    heure_sortie TIMESTAMP,
    total_heures_travaillees NUMERIC(5,2),
    status VARCHAR(20) NOT NULL DEFAULT 'ABSENT',
    overtime_hours NUMERIC(5,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_presence_user_day UNIQUE (utilisateur_id, date_presence)
);

CREATE INDEX idx_presences_user ON presences (utilisateur_id);
