"""Slice 6 — Ollama/Qwen provider tracing.

Tests for a uniform per-turn metadata annotation that lets observability /
frontend answer "did this turn use the LLM? which provider/model?".

Pure metadata. Does not change what the LLM does or when it is called.
"""
from __future__ import annotations

import pytest

from app.context.current_user import CurrentUserContext
from app.models.agent_models import AgentResponse, ToolCallRecord
from app.observability.provider_metadata import annotate_provider_metadata
from app.providers.router import ProviderRouter


def _router() -> ProviderRouter:
    return ProviderRouter(
        mode="ollama",
        providers={"ollama": _StubProvider()},
        default_model="qwen2.5:3b",
        fallback_model="phi3",
    )


def _disabled_router() -> ProviderRouter:
    return ProviderRouter(mode="disabled", default_model=None)


class _StubProvider:
    def provider_name(self) -> str:
        return "ollama"

    def supports_streaming(self) -> bool:
        return False

    def supports_tools(self) -> bool:
        return False


# ---------- Deterministic agent path (most turns) ---------------------------


def test_deterministic_response_gets_llm_used_false() -> None:
    response = AgentResponse(
        type="answer",
        text="Voici votre solde de conges.",
        intent="leave.balance",
        confidence=0.9,
        actionResult={"kind": "read_result", "data": {"total": 12}},
    )

    out = annotate_provider_metadata(response, provider_router=_router(), intent_before_llm="leave.balance")

    assert isinstance(out.actionResult, dict)
    assert out.actionResult["llm_used"] is False
    assert out.actionResult["provider"] == "ollama"
    assert out.actionResult["model"] == "qwen2.5:3b"
    assert out.actionResult["intent_before_llm"] == "leave.balance"
    assert "intent_after_llm" not in out.actionResult or out.actionResult["intent_after_llm"] is None
    # Existing fields preserved
    assert out.actionResult["kind"] == "read_result"
    assert out.actionResult["data"] == {"total": 12}


def test_response_with_no_action_result_gets_dict_with_metadata() -> None:
    response = AgentResponse(
        type="ask",
        text="Pour quelle date ?",
        intent="leave.create",
        confidence=0.9,
        actionResult=None,
    )

    out = annotate_provider_metadata(response, provider_router=_router(), intent_before_llm="leave.create")

    assert isinstance(out.actionResult, dict)
    assert out.actionResult["llm_used"] is False
    assert out.actionResult["provider"] == "ollama"
    assert out.actionResult["model"] == "qwen2.5:3b"
    assert out.actionResult["intent_before_llm"] == "leave.create"


# ---------- Provider-used path (rare — provider_response kind) --------------


def test_provider_response_kind_gets_llm_used_true() -> None:
    response = AgentResponse(
        type="answer",
        text="Generated by LLM.",
        intent="provider.response",
        confidence=0.0,
        actionResult={
            "kind": "provider_response",
            "providerName": "ollama",
            "model": "qwen2.5:3b",
            "latencyMs": 123.4,
        },
    )

    out = annotate_provider_metadata(response, provider_router=_router(), intent_before_llm="fallback.unknown")

    assert out.actionResult["llm_used"] is True
    assert out.actionResult["provider"] == "ollama"
    # When the provider response carries its own model, prefer that.
    assert out.actionResult["model"] == "qwen2.5:3b"
    assert out.actionResult["intent_before_llm"] == "fallback.unknown"
    assert out.actionResult["intent_after_llm"] == "provider.response"


def test_wording_enhancement_gets_llm_used_true_without_changing_intent() -> None:
    response = AgentResponse(
        type="answer",
        text="Texte ameliore par Ollama.",
        intent="attendance.status",
        confidence=0.9,
        actionResult={
            "kind": "read_result",
            "providerUsed": "ollama",
            "model": "qwen2.5:3b",
            "enhancementApplied": True,
            "fallbackUsed": False,
        },
    )

    out = annotate_provider_metadata(response, provider_router=_router(), intent_before_llm="attendance.status")

    assert out.actionResult["llm_used"] is True
    assert out.actionResult["enhancementApplied"] is True
    assert out.actionResult["provider"] == "ollama"
    assert out.actionResult["model"] == "qwen2.5:3b"
    assert out.actionResult["intent_before_llm"] == "attendance.status"
    assert out.actionResult["intent_after_llm"] == "attendance.status"


# ---------- Disabled provider mode ------------------------------------------


def test_disabled_mode_reports_provider_disabled() -> None:
    response = AgentResponse(
        type="answer",
        text="Voici votre solde.",
        intent="leave.balance",
        confidence=0.9,
        actionResult={"kind": "read_result"},
    )

    out = annotate_provider_metadata(response, provider_router=_disabled_router(), intent_before_llm="leave.balance")

    assert out.actionResult["llm_used"] is False
    assert out.actionResult["provider"] == "disabled"
    # default_model is None when disabled — metadata reflects that honestly.
    assert out.actionResult["model"] is None


# ---------- Fallback / deterministic_fallback kind --------------------------


def test_deterministic_fallback_kind_does_not_overwrite_provider_used() -> None:
    """The existing FallbackMetadata.provider_used literal is preserved (it's
    constrained to 'none' by the schema). We layer new keys without touching
    it."""
    response = AgentResponse(
        type="error",
        text="Je ne peux pas confirmer cette information.",
        intent="fallback.guard_rejected",
        confidence=1.0,
        actionResult={
            "kind": "deterministic_fallback",
            "fallback_used": True,
            "fallback_reason": "guard_rejected",
            "provider_used": "none",
        },
    )

    out = annotate_provider_metadata(response, provider_router=_router(), intent_before_llm="leave.balance")

    assert out.actionResult["llm_used"] is False
    assert out.actionResult["provider"] == "ollama"
    assert out.actionResult["model"] == "qwen2.5:3b"
    # Existing field untouched
    assert out.actionResult["provider_used"] == "none"
    assert out.actionResult["fallback_reason"] == "guard_rejected"


# ---------- Idempotency / re-annotation -------------------------------------


def test_annotation_is_idempotent() -> None:
    response = AgentResponse(
        type="answer",
        text="ok",
        intent="leave.balance",
        confidence=0.9,
        actionResult={"kind": "read_result"},
    )

    once = annotate_provider_metadata(response, provider_router=_router(), intent_before_llm="leave.balance")
    twice = annotate_provider_metadata(once, provider_router=_router(), intent_before_llm="leave.balance")

    assert twice.actionResult["llm_used"] is False
    assert twice.actionResult["provider"] == "ollama"


# ---------- Don't regress core response fields ------------------------------


def test_text_and_intent_are_not_modified() -> None:
    response = AgentResponse(
        type="confirm_action",
        text="Confirmez-vous cette demande ?",
        intent="leave.create",
        confidence=0.9,
        requiresConfirmation=True,
        confirmationId="cf-1",
        toolCalls=[ToolCallRecord(name="leave.create_request", arguments={}, status="pending_confirmation")],
        actionResult={"kind": "confirmation_summary", "summary": {"type": "annuel"}},
    )

    out = annotate_provider_metadata(response, provider_router=_router(), intent_before_llm="leave.create")

    assert out.text == "Confirmez-vous cette demande ?"
    assert out.intent == "leave.create"
    assert out.type == "confirm_action"
    assert out.requiresConfirmation is True
    assert out.confirmationId == "cf-1"
    assert out.toolCalls[0].name == "leave.create_request"
    assert out.actionResult["kind"] == "confirmation_summary"
    assert out.actionResult["summary"] == {"type": "annuel"}


# ---------- Configured but provider not used (e.g. provider_response kind missing) ---


@pytest.mark.parametrize("kind", ["read_result", "write_result", "manager_pending_summary", "capability_unavailable", "greeting"])
def test_various_deterministic_kinds_get_llm_used_false(kind: str) -> None:
    response = AgentResponse(
        type="answer",
        text="ok",
        intent="some.intent",
        confidence=0.8,
        actionResult={"kind": kind},
    )

    out = annotate_provider_metadata(response, provider_router=_router(), intent_before_llm="some.intent")

    assert out.actionResult["llm_used"] is False
    assert out.actionResult["kind"] == kind
