from __future__ import annotations

from app.core.response_types import SAFE_CHATBOT_RESPONSE_CONTRACTS

SAFE_TOOL_CALL_STATUSES = {
    "success",
    "failed",
    "pending",
    "pending_confirmation",
    "business_conflict",
    "denied",
}

SAFE_NO_EVIDENCE_INTENTS = {
    "greeting",
    "system.greeting",
    "fallback.unknown",
    "chat",
    "leave.cancelled",
    "leave.create.cancelled",
    "authorization.create.cancelled",
    "authorization.cancelled",
    "telework.create.cancelled",
    "telework.cancelled",
    "conversation.explain_last_error",
    "capability.unavailable",
    "planning.unavailable",
    "planning_horaires.unavailable",
    "meeting.unavailable",
    "meetings.unavailable",
    "reunion.unavailable",
    "rh.create_user_unavailable",
    "rh.organisation_assignment_unavailable",
    "admin.create_user_unavailable",
    "admin.assign_user_unavailable",
    "authorization.info",
    "authorization.types",
    "authorization.create.ask",
    "leave.create.ask",
    "telework.create.ask",
    "document.create.ask",
    "manager.pending_approvals",
    "manager.team_requests",
    "manager.team_schedule",
    "manager.team_presence",
    "manager.team_attendance",
    "planning.list",
    "meetings.list",
}

SAFE_AUTHORITATIVE_RESPONSE_KINDS = set(SAFE_CHATBOT_RESPONSE_CONTRACTS) | {
    "write_result",
    "policy_answer",
    "role_intelligence_digest",
    "insight_report",
    "rh_request_summary",
    "rh_capability_unavailable",
    "approval_lookup",
    "greeting",
    "capability_hint",
    "system_health_report",
    "provider_status_report",
    "redis_status_report",
    "braintrust_status_report",
    "rag_status_report",
    "diagnostics_summary",
    "slot_filling",
    "confirmation_summary",
    "confirmation_result",
    "manager_pending_summary",
    "communication_summary",
    "voice_role_briefing",
    "session_recovery",
    "error_explanation",
}
