-- 1. Create type_autorisations table
CREATE TABLE public.type_autorisations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    libelle character varying(255) NOT NULL,
    max_heures_mois integer,
    require_justificatif boolean,
    CONSTRAINT type_autorisations_pkey PRIMARY KEY (id),
    CONSTRAINT uk_type_autorisations_libelle UNIQUE (libelle)
);

-- 2. Seed default values
INSERT INTO public.type_autorisations (libelle, max_heures_mois, require_justificatif) VALUES 
('SORTIE_ANTICIPEE', 4, false),
('ARRIVEE_TARDIVE', 4, false),
('ABSENCE_TEMPORAIRE', 8, false),
('AUTRE', NULL, false);

-- 3. Add type_autorisation_id to autorisations table
ALTER TABLE public.autorisations ADD COLUMN type_autorisation_id bigint;

-- 4. Migrate data from old type_autorisation column
UPDATE public.autorisations a
SET type_autorisation_id = ta.id
FROM public.type_autorisations ta
WHERE a.type_autorisation = ta.libelle;

-- 5. Add foreign key constraint
ALTER TABLE public.autorisations
    ADD CONSTRAINT fk_autorisations_type_autorisation FOREIGN KEY (type_autorisation_id) REFERENCES public.type_autorisations(id);

-- 6. Make type_autorisation_id NOT NULL after migration
ALTER TABLE public.autorisations ALTER COLUMN type_autorisation_id SET NOT NULL;

-- 7. Drop old column and its check constraint
ALTER TABLE public.autorisations DROP CONSTRAINT autorisations_type_autorisation_check;
ALTER TABLE public.autorisations DROP COLUMN type_autorisation;
