-- 1. Create type_documents table
CREATE TABLE public.type_documents (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    libelle character varying(255) NOT NULL,
    code character varying(255) NOT NULL,
    require_signature boolean DEFAULT false,
    enable_template boolean DEFAULT false,
    CONSTRAINT type_documents_pkey PRIMARY KEY (id),
    CONSTRAINT uk_type_documents_code UNIQUE (code)
);

-- 2. Seed default values from enum
INSERT INTO public.type_documents (libelle, code, require_signature, enable_template) VALUES 
('Attestation de travail', 'ATTESTATION_TRAVAIL', false, true),
('Bulletin de paie', 'BULLETIN_PAIE', false, false),
('Attestation de salaire', 'ATTESTATION_SALAIRE', false, true),
('Contrat de travail', 'CONTRAT_TRAVAIL', true, true),
('Certificat de congé', 'CERTIFICAT_CONGE', false, true),
('Attestation d''ancienneté', 'ATTESTATION_ANCIENNETE', false, true),
('Fiche de poste', 'FICHE_POSTE', false, true);

-- 3. Add type_document_id to documents table
ALTER TABLE public.documents ADD COLUMN type_document_id bigint;

-- 4. Migrate data from old type_document column
UPDATE public.documents d
SET type_document_id = td.id
FROM public.type_documents td
WHERE d.type_document = td.code;

-- 5. Add foreign key constraint
ALTER TABLE public.documents
    ADD CONSTRAINT fk_documents_type_document FOREIGN KEY (type_document_id) REFERENCES public.type_documents(id);

-- 6. Make type_document_id NOT NULL after migration
ALTER TABLE public.documents ALTER COLUMN type_document_id SET NOT NULL;

-- 7. Drop old column
ALTER TABLE public.documents DROP COLUMN type_document;
