
CREATE TABLE public.absences (
    id bigint NOT NULL,
    date_debut date NOT NULL,
    date_declaration date NOT NULL,
    date_fin date NOT NULL,
    justificatif character varying(255),
    motif character varying(255),
    statut character varying(255) NOT NULL,
    type_absence_id bigint NOT NULL,
    demande_id bigint NOT NULL,
    CONSTRAINT absences_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_ATTENTE'::character varying, 'JUSTIFIEE'::character varying, 'INJUSTIFIEE'::character varying, 'ANNULEE'::character varying])::text[])))
);



ALTER TABLE public.absences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;



CREATE TABLE public.autorisations (
    duree integer,
    heure_debut time(0) without time zone,
    heure_fin time(0) without time zone,
    type_autorisation character varying(255) NOT NULL,
    demande_id bigint NOT NULL,
    CONSTRAINT autorisations_type_autorisation_check CHECK (((type_autorisation)::text = ANY ((ARRAY['SORTIE_ANTICIPEE'::character varying, 'ARRIVEE_TARDIVE'::character varying, 'ABSENCE_TEMPORAIRE'::character varying, 'AUTRE'::character varying])::text[])))
);



CREATE TABLE public.conges (
    date_debut date,
    date_fin date,
    justificatif_fourni boolean,
    nombre_jours integer,
    demande_id bigint NOT NULL,
    type_conge_id bigint NOT NULL
);



CREATE TABLE public.demandes (
    id bigint NOT NULL,
    commentaire character varying(1000),
    commentaire_validateur character varying(1000),
    date_creation timestamp(6) without time zone NOT NULL,
    date_decision timestamp(6) without time zone,
    motif character varying(1000),
    statut character varying(255) NOT NULL,
    type_demande character varying(255) NOT NULL,
    manager_id bigint,
    utilisateur_id bigint NOT NULL,
    version bigint,
    CONSTRAINT demandes_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_ATTENTE'::character varying, 'APPROUVEE'::character varying, 'REFUSEE'::character varying, 'ANNULEE'::character varying])::text[]))),
    CONSTRAINT demandes_type_demande_check CHECK (((type_demande)::text = ANY ((ARRAY['CONGE'::character varying, 'AUTORISATION'::character varying, 'DOCUMENT'::character varying, 'TELETRAVAIL'::character varying])::text[])))
);



ALTER TABLE public.demandes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;



CREATE TABLE public.documents (
    nombre_exemplaires integer,
    type_document character varying(255) NOT NULL,
    demande_id bigint NOT NULL
);


CREATE TABLE public.solde_conges (
    id bigint NOT NULL,
    annee integer,
    date_maj timestamp(6) without time zone,
    jours_acquis double precision,
    jours_en_attente double precision,
    jours_restants double precision,
    jours_utilises double precision,
    type_conge_id bigint NOT NULL,
    utilisateur_id bigint NOT NULL
);


ALTER TABLE public.solde_conges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;



CREATE TABLE public.teletravails (
    adresse character varying(255) NOT NULL,
    date_debut date NOT NULL,
    date_fin date NOT NULL,
    nombre_jours integer,
    demande_id bigint NOT NULL
);


CREATE TABLE public.type_absences (
    id bigint NOT NULL,
    decompte_jours boolean,
    libelle character varying(255) NOT NULL,
    nombre_jours_max integer,
    require_justificatif boolean,
    type character varying(255) NOT NULL,
    CONSTRAINT type_absences_type_check CHECK (((type)::text = ANY ((ARRAY['MALADIE'::character varying, 'ACCIDENT_TRAVAIL'::character varying, 'CONGE_MATERNITE'::character varying, 'CONGE_PATERNITE'::character varying, 'ABSENCE_INJUSTIFIEE'::character varying, 'EVENEMENT_FAMILIAL'::character varying, 'AUTRE'::character varying])::text[])))
);



ALTER TABLE public.type_absences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;



CREATE TABLE public.type_conges (
    id bigint NOT NULL,
    decompte_jours boolean,
    libelle character varying(255) NOT NULL,
    nombre_jours_max integer,
    require_justificatif boolean
);



ALTER TABLE public.type_conges ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;



ALTER TABLE public.absences
    ADD CONSTRAINT absences_pkey PRIMARY KEY (id);



ALTER TABLE public.autorisations
    ADD CONSTRAINT autorisations_pkey PRIMARY KEY (demande_id);



ALTER TABLE public.conges
    ADD CONSTRAINT conges_pkey PRIMARY KEY (demande_id);



ALTER TABLE public.demandes
    ADD CONSTRAINT demandes_pkey PRIMARY KEY (id);



ALTER TABLE public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (demande_id);


ALTER TABLE public.solde_conges
    ADD CONSTRAINT solde_conges_pkey PRIMARY KEY (id);



ALTER TABLE public.teletravails
    ADD CONSTRAINT teletravails_pkey PRIMARY KEY (demande_id);



ALTER TABLE public.type_absences
    ADD CONSTRAINT type_absences_pkey PRIMARY KEY (id);



ALTER TABLE public.type_conges
    ADD CONSTRAINT type_conges_pkey PRIMARY KEY (id);



ALTER TABLE public.solde_conges
    ADD CONSTRAINT uk92rmk1qdrobrdstl8n39ungsh UNIQUE (utilisateur_id, type_conge_id, annee);



ALTER TABLE public.conges
    ADD CONSTRAINT fk1fx16iwbphf8enkld4ewwv857 FOREIGN KEY (demande_id) REFERENCES public.demandes(id);



ALTER TABLE public.teletravails
    ADD CONSTRAINT fkd25tgyjk28ej5cvo62ftk0iy FOREIGN KEY (demande_id) REFERENCES public.demandes(id);


ALTER TABLE public.conges
    ADD CONSTRAINT fkdn4jur240qhxdlavuc44uxs8i FOREIGN KEY (type_conge_id) REFERENCES public.type_conges(id);



ALTER TABLE public.absences
    ADD CONSTRAINT fkdqfdjdeoeuow5ulawxx79xruf FOREIGN KEY (demande_id) REFERENCES public.demandes(id);



ALTER TABLE public.autorisations
    ADD CONSTRAINT fkiqwbui6poaa5awp14xkh255qf FOREIGN KEY (demande_id) REFERENCES public.demandes(id);



ALTER TABLE public.absences
    ADD CONSTRAINT fknxjh613eft8b0fm2v6vt0vqi7 FOREIGN KEY (type_absence_id) REFERENCES public.type_absences(id);



ALTER TABLE public.solde_conges
    ADD CONSTRAINT fko7icvplqjkf8plreq0pemptoj FOREIGN KEY (type_conge_id) REFERENCES public.type_conges(id);



ALTER TABLE public.documents
    ADD CONSTRAINT fkrbdn0u42l4s6ul0stnjsk16yi FOREIGN KEY (demande_id) REFERENCES public.demandes(id);



